apiVersion: v1
kind: Service
metadata:
  name: ecommerce
spec:
  type: NodePort
  selector:
    app: ecommerce-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
